services:
  - type: web
    name: canvas-proctor-gateway
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: BASE_URL
        sync: false
      - key: LTI_KEY
        sync: false
      - key: LTI_SECRET
        sync: false
